/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InsertionSort */

#ifndef _Included_InsertionSort
#define _Included_InsertionSort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     InsertionSort
 * Method:    insertionSortMethod
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)I
 */
JNIEXPORT jint JNICALL Java_InsertionSort_insertionSortMethod
  (JNIEnv *, jobject, jstring, jstring, jdouble);

#ifdef __cplusplus
}
#endif
#endif
